local hl = vim.api.nvim_set_hl
local colors = require("dutchpro.colors")
theme = {}

theme.hl = function()
  -- Base highlights
  hl(0, "Normal", { fg = colors.fg, bg = colors.bg })
  hl(0, "Cursor", { fg = colors.cursorL, bg = colors.cursorD })
  hl(0, "CursorLine", { bg = colors.cursorD })
  hl(0, "CursorColumn", { bg = colors.cursorD })
  hl(0, "ColorColumn", { bg = colors.gray })
  hl(0, "Directory", { fg = colors.aqua, bg = "NONE" })
  hl(0, "netrwClassify", { fg = colors.aqua, bg = "NONE" })
  hl(0, "netrwPlain", { fg = colors.grisC, bg = "NONE" })
  hl(0, "ErrorMsg", { fg = colors.err, bg = "NONE" })

  -- Git
  hl(0, "DiffAdd", { fg = "NONE", bg = colors.Dadd })
  hl(0, "DiffChange", { fg = "NONE", bg = colors.dchange })
  hl(0, "DiffDelete", { fg = "NONE", bg = colors.Ddelete })
  hl(0, "DiffText", { fg = "NONE", bg = colors.Dtext })

  -- Folds
  hl(0, "Folded", { fg = "NONE", bg = colors.cursorL })
  hl(0, "FoldColumn", { fg = colors.fg, bg = colors.cursorL })

  -- Signs and Line Numbers
  hl(0, "SignColumn", { fg = "NONE", bg = colors.black })
  hl(0, "LineNr", { fg = colors.Lnumber, bg = "NONE" })
  hl(0, "CursorLineNr", { fg = colors.Lnumber, bg = colors.Lnumber })
  hl(0, "NonText", { fg = colors.Lnumber, bg = "NONE" })
  hl(0, "EndOfBuffer", { fg = colors.Lnumber, bg = "NONE" })

  -- Splits
  hl(0, "VertSplit", { fg = colors.gris, bg = "NONE" })
  hl(0, "Split", { fg = colors.gris, bg = "NONE" })

  -- UI Elements
  hl(0, "Title", { fg = colors.aqua, bg = "NONE" })
  hl(0, "Search", { fg = colors.black, bg = colors.yellow })
  hl(0, "IncSearch", { fg = colors.black, bg = colors.aqua })
  hl(0, "WarningMsg", { fg = colors.err, bg = "NONE", bold = true })
  hl(0, "Question", { fg = colors.gray, bg = colors.black })
  hl(0, "SpecialKey", { fg = colors.special, bg = "NONE" })
  hl(0, "MatchParen", { fg = colors.aqua, bg = colors.cursorD, bold = true })

  -- Popup Menu
  hl(0, "Pmenu", { fg = colors.fg, bg = colors.gray })
  hl(0, "PmenuSel", { fg = colors.fg, bg = colors.cursorD })
  hl(0, "PmenuSbar", { fg = "NONE", bg = colors.gray })
  hl(0, "PmenuThumb", { fg = "NONE", bg = colors.gris })
  hl(0, "WildMenu", { fg = "NONE", bg = colors.cursorD })

  -- Tabs
  hl(0, "TabLine", { fg = colors.fg, bg = colors.mod })
  hl(0, "TabLineFill", { fg = colors.fg, bg = colors.gray })
  hl(0, "TabLineSel", { fg = colors.fg, bg = colors.cursorD })

  -- Visual
  hl(0, "Visual", { fg = "NONE", bg = colors.cursorD })
  hl(0, "VisualNOS", { fg = "NONE", bg = colors.cursorD })

  -- Statusline
  hl(0, "StatusLine", { fg = colors.fg, bg = colors.gray })
  hl(0, "StatusLineNC", { fg = colors.gris, bg = colors.gray })

  -- General Language Syntax
  hl(0, "Comment", { fg = colors.comment, bg = "NONE", italic = true })
  hl(0, "Constant", { fg = colors.Constant, bg = "NONE" })
  hl(0, "String", { fg = colors.String, bg = "NONE" })
  hl(0, "Character", { fg = colors.grisC, bg = "NONE" })
  hl(0, "Number", { fg = colors.Number, bg = "NONE" })
  hl(0, "Boolean", { fg = colors.Boolean, bg = "NONE" })
  hl(0, "Float", { fg = colors.Float, bg = "NONE" })

  hl(0, "Identifier", { fg = colors.Identifier, bg = "NONE" })
  hl(0, "Function", { fg = colors.Function, bg = "NONE" })

  hl(0, "Statement", { fg = colors.Statement, bg = "NONE" })
  hl(0, "Conditional", { fg = colors.Conditional, bg = "NONE" })
  hl(0, "Repeat", { fg = colors.Repeat, bg = "NONE" })
  hl(0, "Label", { fg = colors.Label, bg = "NONE" })
  hl(0, "Operator", { fg = colors.operator, bg = "NONE" })
  hl(0, "Keyword", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "Exception", { fg = colors.Exception, bg = "NONE" })

  hl(0, "PreProc", { fg = colors.PreProc, bg = "NONE" })
  hl(0, "Include", { fg = colors.Include, bg = "NONE" })
  hl(0, "Define", { fg = colors.Define, bg = "NONE" })
  hl(0, "Macro", { fg = colors.Macro, bg = "NONE" })
  hl(0, "PreCondit", { fg = colors.PreProc, bg = "NONE" })

  hl(0, "Type", { fg = colors.Type, bg = "NONE" })
  hl(0, "StorageClass", { fg = colors.Class, bg = "NONE" })
  hl(0, "Structure", { fg = colors.Structure, bg = "NONE" })
  hl(0, "Typedef", { fg = colors.DefType, bg = "NONE" })

  hl(0, "Special", { fg = colors.special, bg = "NONE" })
  hl(0, "SpecialChar", { fg = colors.escape, bg = "NONE" })
  hl(0, "Tag", { fg = colors.tag, bg = "NONE" })
  hl(0, "Delimiter", { fg = colors.gris, bg = "NONE" })
  hl(0, "SpecialComment", { fg = colors.comment, bg = "NONE", bold = true })
  hl(0, "Debug", { fg = colors.red, bg = "NONE" })

  -- Treesitter
  hl(0, "@variable", { fg = colors.Variable, bg = "NONE" })
  hl(0, "@variable.builtin", { fg = colors.aqua, bg = "NONE" })
  hl(0, "@variable.parameter", { fg = colors.parameter, bg = "NONE" })
  hl(0, "@variable.member", { fg = colors.props, bg = "NONE" })

  hl(0, "@constant", { fg = colors.Constant, bg = "NONE" })
  hl(0, "@constant.builtin", { fg = colors.Boolean, bg = "NONE" })
  hl(0, "@constant.macro", { fg = colors.Macro, bg = "NONE" })

  hl(0, "@string", { fg = colors.String, bg = "NONE" })
  hl(0, "@string.escape", { fg = colors.escape, bg = "NONE" })
  hl(0, "@string.special", { fg = colors.Spec, bg = "NONE" })
  hl(0, "@character", { fg = colors.grisC, bg = "NONE" })

  hl(0, "@number", { fg = colors.Number, bg = "NONE" })
  hl(0, "@boolean", { fg = colors.Boolean, bg = "NONE" })
  hl(0, "@float", { fg = colors.Float, bg = "NONE" })

  hl(0, "@function", { fg = colors.FuncName, bg = "NONE" })
  hl(0, "@function.builtin", { fg = colors.aqua, bg = "NONE" })
  hl(0, "@function.call", { fg = colors.FuncCall, bg = "NONE" })
  hl(0, "@function.macro", { fg = colors.Macro, bg = "NONE" })
  hl(0, "@function.method", { fg = colors.FuncCall, bg = "NONE" })
  hl(0, "@function.method.call", { fg = colors.FuncCall, bg = "NONE" })

  hl(0, "@constructor", { fg = colors.ClassCall, bg = "NONE" })
  hl(0, "@parameter", { fg = colors.parameter, bg = "NONE" })

  hl(0, "@keyword", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "@keyword.function", { fg = colors.Function, bg = "NONE" })
  hl(0, "@keyword.operator", { fg = colors.operator, bg = "NONE" })
  hl(0, "@keyword.return", { fg = colors.Keyword, bg = "NONE" })

  hl(0, "@conditional", { fg = colors.Conditional, bg = "NONE" })
  hl(0, "@repeat", { fg = colors.Repeat, bg = "NONE" })
  hl(0, "@label", { fg = colors.Label, bg = "NONE" })
  hl(0, "@operator", { fg = colors.operator, bg = "NONE" })
  hl(0, "@exception", { fg = colors.Exception, bg = "NONE" })

  hl(0, "@type", { fg = colors.Type, bg = "NONE" })
  hl(0, "@type.builtin", { fg = colors.Type, bg = "NONE" })
  hl(0, "@type.definition", { fg = colors.DefType, bg = "NONE" })
  hl(0, "@type.qualifier", { fg = colors.Keyword, bg = "NONE" })

  hl(0, "@property", { fg = colors.props, bg = "NONE" })
  hl(0, "@attribute", { fg = colors.attribute, bg = "NONE" })

  hl(0, "@namespace", { fg = colors.aqua, bg = "NONE" })
  hl(0, "@symbol", { fg = colors.aqua, bg = "NONE" })

  hl(0, "@tag", { fg = colors.tagName, bg = "NONE" })
  hl(0, "@tag.attribute", { fg = colors.TagArg, bg = "NONE" })
  hl(0, "@tag.delimiter", { fg = colors.grisC, bg = "NONE" })

  hl(0, "@punctuation.delimiter", { fg = colors.gris, bg = "NONE" })
  hl(0, "@punctuation.bracket", { fg = colors.gris, bg = "NONE" })
  hl(0, "@punctuation.special", { fg = colors.grisC, bg = "NONE" })

  hl(0, "@comment", { fg = colors.comment, bg = "NONE", italic = true })

  -- HTML
  hl(0, "htmlTag", { fg = colors.grisC, bg = "NONE" })
  hl(0, "htmlTagN", { fg = colors.grisC, bg = "NONE" })
  hl(0, "htmlEndTag", { fg = colors.grisC, bg = "NONE" })
  hl(0, "htmlTagName", { fg = colors.tagName, bg = "NONE" })
  hl(0, "htmlSpecialTagName", { fg = colors.tagName, bg = "NONE" })
  hl(0, "htmlArg", { fg = colors.TagArg, bg = "NONE" })
  hl(0, "htmlLink", { fg = colors.aqua, bg = "NONE", underline = true })

  -- CSS
  hl(0, "cssBraces", { fg = colors.gris, bg = "NONE" })
  hl(0, "cssInclude", { fg = colors.Decorator, bg = "NONE" })
  hl(0, "cssTagName", { fg = colors.Statement, bg = "NONE" })
  hl(0, "cssClassName", { fg = colors.aqua, bg = "NONE" })
  hl(0, "cssPseudoClass", { fg = colors.yellow, bg = "NONE" })
  hl(0, "cssPseudoClassId", { fg = colors.aqua, bg = "NONE" })
  hl(0, "cssIdentifier", { fg = colors.BlueDark, bg = "NONE" })
  hl(0, "cssProp", { fg = colors.props, bg = "NONE" })
  hl(0, "cssAttr", { fg = colors.attribute, bg = "NONE" })
  hl(0, "cssAttrRegion", { fg = colors.gris, bg = "NONE" })
  hl(0, "cssAtRule", { fg = colors.BlueDark, bg = "NONE" })
  hl(0, "cssDefinition", { fg = colors.aqua, bg = "NONE" })
  hl(0, "cssFunction", { fg = colors.Function, bg = "NONE" })
  hl(0, "cssFunctionName", { fg = colors.aqua, bg = "NONE" })
  hl(0, "cssValueNumber", { fg = colors.Number, bg = "NONE" })
  hl(0, "cssValueLength", { fg = colors.Number, bg = "NONE" })
  hl(0, "cssUnitDecorators", { fg = colors.Decorators, bg = "NONE" })
  hl(0, "cssStyle", { fg = colors.aqua, bg = "NONE" })
  hl(0, "cssColor", { fg = colors.Number, bg = "NONE" })
  hl(0, "cssImportant", { fg = colors.Function, bg = "NONE", bold = true })

  -- JavaScript
  hl(0, "jsVariableDef", { fg = colors.Variable, bg = "NONE" })
  hl(0, "jsFuncArgs", { fg = colors.argument, bg = "NONE" })
  hl(0, "jsFuncBlock", { fg = colors.Function, bg = "NONE" })
  hl(0, "jsRegexpString", { fg = colors.escape, bg = "NONE", bold = true })
  hl(0, "javaScriptStringS", { fg = colors.String, bg = "NONE" })
  hl(0, "javaScriptStringT", { fg = colors.Spec, bg = "NONE" })
  hl(0, "javaScriptEmbed", { fg = colors.Spec, bg = "NONE" })
  hl(0, "javascriptOperator", { fg = colors.operator, bg = "NONE" })
  hl(0, "jsDestructuringBlock", { fg = colors.operator, bg = "NONE" })
  hl(0, "javaScriptIdentifier", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "javaScriptReserved", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "javaScriptNumber", { fg = colors.Number, bg = "NONE" })
  hl(0, "javaScriptBraces", { fg = colors.gris, bg = "NONE" })
  hl(0, "jsObjectKey", { fg = colors.props, bg = "NONE" })
  hl(0, "jsModuleKeyword", { fg = colors.Function, bg = "NONE" })
  hl(0, "jsClassDefinition", { fg = colors.ClassName, bg = "NONE" })
  hl(0, "jsExportDefault", { fg = colors.Function, bg = "NONE" })
  hl(0, "jsFuncCall", { fg = colors.FuncCall, bg = "NONE" })
  hl(0, "jsObjectValue", { fg = colors.Variable, bg = "NONE" })
  hl(0, "jsObjectProp", { fg = colors.props, bg = "NONE" })
  hl(0, "jsSpreadOperator", { fg = colors.operator, bg = "NONE" })
  hl(0, "jsSpreadExpression", { fg = colors.operator, bg = "NONE" })
  hl(0, "jsThis", { fg = colors.aqua, bg = "NONE" })
  hl(0, "jsSuper", { fg = colors.aqua, bg = "NONE" })

  -- Golang
  hl(0, "goPackage", { fg = colors.Function, bg = "NONE" })
  hl(0, "goImport", { fg = colors.Function, bg = "NONE" })
  hl(0, "goVar", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "goBlock", { fg = colors.gris, bg = "NONE" })
  hl(0, "goConst", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "goStatement", { fg = colors.Function, bg = "NONE" })
  hl(0, "goType", { fg = colors.Type, bg = "NONE" })
  hl(0, "goSignedInts", { fg = colors.Type, bg = "NONE" })
  hl(0, "goUnsignedInts", { fg = colors.Type, bg = "NONE" })
  hl(0, "goFloats", { fg = colors.Type, bg = "NONE" })
  hl(0, "goComplexes", { fg = colors.Type, bg = "NONE" })
  hl(0, "goBuiltins", { fg = colors.aqua, bg = "NONE" })
  hl(0, "goBoolean", { fg = colors.Boolean, bg = "NONE" })
  hl(0, "goPredefinedIdentifiers", { fg = colors.aqua, bg = "NONE" })
  hl(0, "goDeclaration", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "goDeclType", { fg = colors.Type, bg = "NONE" })
  hl(0, "goTypeDecl", { fg = colors.Type, bg = "NONE" })
  hl(0, "goTypeName", { fg = colors.Type, bg = "NONE" })
  hl(0, "goFunctionCall", { fg = colors.FuncCall, bg = "NONE" })
  hl(0, "goMethodCall", { fg = colors.FuncCall, bg = "NONE" })

  -- Python
  hl(0, "pythonStatement", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "pythonRepeat", { fg = colors.Repeat, bg = "NONE" })
  hl(0, "pythonException", { fg = colors.Exception, bg = "NONE" })
  hl(0, "pythonFunction", { fg = colors.Function, bg = "NONE" })
  hl(0, "pythonConditional", { fg = colors.Conditional, bg = "NONE" })
  hl(0, "pythonBuiltin", { fg = colors.aqua, bg = "NONE" })
  hl(0, "pythonString", { fg = colors.String, bg = "NONE" })
  hl(0, "pythonAttribute", { fg = colors.attribute, bg = "NONE" })
  hl(0, "pythonDecorator", { fg = colors.Decorator, bg = "NONE" })
  hl(0, "pythonDecoratorName", { fg = colors.Decorator, bg = "NONE" })
  hl(0, "pythonEscape", { fg = colors.escape, bg = "NONE", bold = true })
  hl(0, "pythonInclude", { fg = colors.Include, bg = "NONE" })
  hl(0, "pythonQuotes", { fg = colors.Quotes, bg = "NONE" })
  hl(0, "pythonRawString", { fg = colors.String, bg = "NONE", bold = true })
  hl(0, "pythonBuiltinObj", { fg = colors.ClassObj, bg = "NONE" })
  hl(0, "pythonTripleQuotes", { fg = colors.Quotes, bg = "NONE" })
  hl(0, "pythonBuiltinType", { fg = colors.Type, bg = "NONE" })
  hl(0, "pythonBoolean", { fg = colors.Boolean, bg = "NONE" })
  hl(0, "pythonNone", { fg = colors.None, bg = "NONE" })
  hl(0, "pythonClassVar", { fg = colors.aqua, bg = "NONE" })
  hl(0, "pythonClassDef", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "pythonClassName", { fg = colors.ClassName, bg = "NONE" })
  hl(0, "pythonOperator", { fg = colors.operator, bg = "NONE" })
  hl(0, "pythonSelf", { fg = colors.aqua, bg = "NONE" })
  hl(0, "pythonDottedName", { fg = colors.ClassCall, bg = "NONE" })

  -- Lua
  hl(0, "luaFunc", { fg = colors.aqua, bg = "NONE" })
  hl(0, "luaCond", { fg = colors.Conditional, bg = "NONE" })
  hl(0, "luaStatement", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "luaFunctionBlock", { fg = colors.aqua, bg = "NONE" })
  hl(0, "luaFunction", { fg = colors.Function, bg = "NONE" })
  hl(0, "luaFuncCall", { fg = colors.FuncCall, bg = "NONE" })
  hl(0, "luaFuncArgName", { fg = colors.argument, bg = "NONE" })
  hl(0, "luaFuncKeyword", { fg = colors.Function, bg = "NONE" })
  hl(0, "luaLocal", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "luaBuiltIn", { fg = colors.aqua, bg = "NONE" })
  hl(0, "luaRepeat", { fg = colors.Repeat, bg = "NONE" })
  hl(0, "luaOperator", { fg = colors.operator, bg = "NONE" })
  hl(0, "luaTable", { fg = colors.gris, bg = "NONE" })
  hl(0, "luaTableBlock", { fg = colors.gris, bg = "NONE" })

  -- Shell
  hl(0, "shDeref", { fg = colors.Variable, bg = "NONE" })
  hl(0, "shFunction", { fg = colors.aqua, bg = "NONE" })
  hl(0, "shVariable", { fg = colors.Variable, bg = "NONE" })
  hl(0, "shStatement", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "shCmdSubRegion", { fg = colors.Decorator, bg = "NONE" })
  hl(0, "shDblBrace", { fg = colors.gris, bg = "NONE" })
  hl(0, "bashSpecialVariables", { fg = colors.aqua, bg = "NONE" })
  hl(0, "shQuote", { fg = colors.String, bg = "NONE" })
  hl(0, "shOption", { fg = colors.yellow, bg = "NONE" })

  -- Rust
  hl(0, "rustMacro", { fg = colors.aqua, bg = "NONE" })
  hl(0, "rustAttribute", { fg = colors.Decorator, bg = "NONE" })
  hl(0, "rustFoldBraces", { fg = colors.gris, bg = "NONE" })
  hl(0, "rustDerive", { fg = colors.BlueDark, bg = "NONE" })
  hl(0, "rustDeriveTrait", { fg = colors.aqua, bg = "NONE" })
  hl(0, "rustTrait", { fg = colors.Type, bg = "NONE" })
  hl(0, "rustIdentifier", { fg = colors.Variable, bg = "NONE" })
  hl(0, "rustOperator", { fg = colors.operator, bg = "NONE" })
  hl(0, "rustKeyword", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "rustModPath", { fg = colors.grisC, bg = "NONE" })
  hl(0, "rustAssert", { fg = colors.aqua, bg = "NONE" })
  hl(0, "rustTypedef", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "rustType", { fg = colors.Type, bg = "NONE" })
  hl(0, "rustBraces", { fg = colors.gris, bg = "NONE" })
  hl(0, "rustVariable", { fg = colors.Variable, bg = "NONE" })
  hl(0, "rustBoxPlacementBalance", { fg = colors.gris, bg = "NONE" })
  hl(0, "rustStorage", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "rustStructure", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "rustSigil", { fg = colors.gris, bg = "NONE" })
  hl(0, "rustFuncName", { fg = colors.FuncName, bg = "NONE" })
  hl(0, "rustFuncCall", { fg = colors.FuncCall, bg = "NONE" })
  hl(0, "rustEnum", { fg = colors.Type, bg = "NONE" })
  hl(0, "rustEnumVariant", { fg = colors.aqua, bg = "NONE" })
  hl(0, "rustSelf", { fg = colors.aqua, bg = "NONE" })
  hl(0, "rustLifetime", { fg = colors.yellow, bg = "NONE" })

  -- Markdown
  hl(0, "markdownH1", { fg = colors.red, bg = "NONE", bold = true })
  hl(0, "markdownH2", { fg = colors.red, bg = "NONE", bold = true })
  hl(0, "markdownH3", { fg = colors.red, bg = "NONE", bold = true })
  hl(0, "markdownH4", { fg = colors.yellow, bg = "NONE", bold = true })
  hl(0, "markdownH5", { fg = colors.yellow, bg = "NONE" })
  hl(0, "markdownH6", { fg = colors.yellow, bg = "NONE" })
  hl(0, "markdownCode", { fg = colors.aqua, bg = "NONE" })
  hl(0, "markdownCodeBlock", { fg = colors.aqua, bg = "NONE" })
  hl(0, "markdownCodeDelimiter", { fg = colors.gris, bg = "NONE" })
  hl(0, "markdownBlockquote", { fg = colors.comment, bg = "NONE", italic = true })
  hl(0, "markdownListMarker", { fg = colors.red, bg = "NONE" })
  hl(0, "markdownOrderedListMarker", { fg = colors.red, bg = "NONE" })
  hl(0, "markdownRule", { fg = colors.gris, bg = "NONE" })
  hl(0, "markdownHeadingRule", { fg = colors.gris, bg = "NONE" })
  hl(0, "markdownUrlDelimiter", { fg = colors.gris, bg = "NONE" })
  hl(0, "markdownLinkDelimiter", { fg = colors.gris, bg = "NONE" })
  hl(0, "markdownLinkTextDelimiter", { fg = colors.gris, bg = "NONE" })
  hl(0, "markdownHeadingDelimiter", { fg = colors.red, bg = "NONE" })
  hl(0, "markdownUrl", { fg = colors.aqua, bg = "NONE" })
  hl(0, "markdownUrlTitleDelimiter", { fg = colors.String, bg = "NONE" })
  hl(0, "markdownLinkText", { fg = colors.yellow, bg = "NONE", underline = true })
  hl(0, "markdownIdDeclaration", { fg = colors.yellow, bg = "NONE" })

  -- JSON
  hl(0, "jsonKeyword", { fg = colors.aqua, bg = "NONE" })
  hl(0, "jsonQuote", { fg = colors.gris, bg = "NONE" })
  hl(0, "jsonBraces", { fg = colors.gris, bg = "NONE" })
  hl(0, "jsonString", { fg = colors.String, bg = "NONE" })

  -- YAML
  hl(0, "yamlKey", { fg = colors.aqua, bg = "NONE" })
  hl(0, "yamlAnchor", { fg = colors.yellow, bg = "NONE" })
  hl(0, "yamlAlias", { fg = colors.yellow, bg = "NONE" })
  hl(0, "yamlDocumentHeader", { fg = colors.comment, bg = "NONE" })

  -- TOML
  hl(0, "tomlTable", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "tomlKey", { fg = colors.aqua, bg = "NONE" })

  -- Git
  hl(0, "gitcommitComment", { fg = colors.comment, bg = "NONE", italic = true })
  hl(0, "gitcommitUnmerged", { fg = colors.red, bg = "NONE", bold = true })
  hl(0, "gitcommitOnBranch", { fg = colors.comment, bg = "NONE", bold = true })
  hl(0, "gitcommitBranch", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "gitcommitDiscardedType", { fg = colors.red, bg = "NONE" })
  hl(0, "gitcommitSelectedType", { fg = colors.String, bg = "NONE" })
  hl(0, "gitcommitHeader", { fg = colors.comment, bg = "NONE" })
  hl(0, "gitcommitUntrackedFile", { fg = colors.red, bg = "NONE" })
  hl(0, "gitcommitDiscardedFile", { fg = colors.red, bg = "NONE" })
  hl(0, "gitcommitSelectedFile", { fg = colors.String, bg = "NONE" })
  hl(0, "gitcommitUnmergedFile", { fg = colors.yellow, bg = "NONE" })
  hl(0, "gitcommitFile", { fg = colors.fg, bg = "NONE" })

  -- Diff
  hl(0, "diffAdded", { fg = colors.String, bg = "NONE" })
  hl(0, "diffRemoved", { fg = colors.red, bg = "NONE" })
  hl(0, "diffChanged", { fg = colors.yellow, bg = "NONE" })
  hl(0, "diffOldFile", { fg = colors.comment, bg = "NONE" })
  hl(0, "diffNewFile", { fg = colors.aqua, bg = "NONE" })
  hl(0, "diffFile", { fg = colors.aqua, bg = "NONE" })
  hl(0, "diffLine", { fg = colors.comment, bg = "NONE" })
  hl(0, "diffIndexLine", { fg = colors.comment, bg = "NONE" })

  -- LSP
  hl(0, "DiagnosticError", { fg = colors.err, bg = "NONE" })
  hl(0, "DiagnosticWarn", { fg = colors.warns, bg = "NONE" })
  hl(0, "DiagnosticInfo", { fg = colors.aqua, bg = "NONE" })
  hl(0, "DiagnosticHint", { fg = colors.comment, bg = "NONE" })
  hl(0, "DiagnosticUnderlineError", { fg = "NONE", bg = "NONE", undercurl = true, sp = colors.err })
  hl(0, "DiagnosticUnderlineWarn", { fg = "NONE", bg = "NONE", undercurl = true, sp = colors.warns })
  hl(0, "DiagnosticUnderlineInfo", { fg = "NONE", bg = "NONE", undercurl = true, sp = colors.aqua })
  hl(0, "DiagnosticUnderlineHint", { fg = "NONE", bg = "NONE", undercurl = true, sp = colors.comment })
  hl(0, "DiagnosticVirtualTextError", { fg = colors.err, bg = "NONE" })
  hl(0, "DiagnosticVirtualTextWarn", { fg = colors.warns, bg = "NONE" })
  hl(0, "DiagnosticVirtualTextInfo", { fg = colors.aqua, bg = "NONE" })
  hl(0, "DiagnosticVirtualTextHint", { fg = colors.comment, bg = "NONE" })
  hl(0, "DiagnosticSignError", { fg = colors.err, bg = "NONE" })
  hl(0, "DiagnosticSignWarn", { fg = colors.warns, bg = "NONE" })
  hl(0, "DiagnosticSignInfo", { fg = colors.aqua, bg = "NONE" })
  hl(0, "DiagnosticSignHint", { fg = colors.comment, bg = "NONE" })

  hl(0, "LspReferenceText", { fg = "NONE", bg = colors.cursorD })
  hl(0, "LspReferenceRead", { fg = "NONE", bg = colors.cursorD })
  hl(0, "LspReferenceWrite", { fg = "NONE", bg = colors.cursorD })

  hl(0, "LspSignatureActiveParameter", { fg = colors.yellow, bg = "NONE", bold = true })

  -- Telescope
  hl(0, "TelescopeSelection", { fg = colors.fg, bg = colors.cursorD })
  hl(0, "TelescopeSelectionCaret", { fg = colors.aqua, bg = colors.cursorD })
  hl(0, "TelescopeMultiSelection", { fg = colors.yellow, bg = "NONE" })
  hl(0, "TelescopeNormal", { fg = colors.fg, bg = "NONE" })
  hl(0, "TelescopeBorder", { fg = colors.gris, bg = "NONE" })
  hl(0, "TelescopePromptBorder", { fg = colors.gris, bg = "NONE" })
  hl(0, "TelescopeResultsBorder", { fg = colors.gris, bg = "NONE" })
  hl(0, "TelescopePreviewBorder", { fg = colors.gris, bg = "NONE" })
  hl(0, "TelescopeMatching", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "TelescopePromptPrefix", { fg = colors.red, bg = "NONE" })

  -- NvimTree
  hl(0, "NvimTreeNormal", { fg = colors.fg, bg = colors.bg })
  hl(0, "NvimTreeRootFolder", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "NvimTreeGitDirty", { fg = colors.yellow, bg = "NONE" })
  hl(0, "NvimTreeGitNew", { fg = colors.String, bg = "NONE" })
  hl(0, "NvimTreeGitDeleted", { fg = colors.red, bg = "NONE" })
  hl(0, "NvimTreeSpecialFile", { fg = colors.yellow, bg = "NONE", underline = true })
  hl(0, "NvimTreeIndentMarker", { fg = colors.gris, bg = "NONE" })
  hl(0, "NvimTreeImageFile", { fg = colors.aqua, bg = "NONE" })
  hl(0, "NVimTreeSymlink", { fg = colors.aqua, bg = "NONE" })
  hl(0, "NvimTreeFolderName", { fg = colors.aqua, bg = "NONE" })
  hl(0, "NvimTreeFolderIcon", { fg = colors.aqua, bg = "NONE" })
  hl(0, "NvimTreeEmptyFolderName", { fg = colors.gris, bg = "NONE" })
  hl(0, "NvimTreeOpenedFolderName", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "NvimTreeExecFile", { fg = colors.String, bg = "NONE", bold = true })
  hl(0, "NvimTreeOpenedFile", { fg = colors.fg, bg = "NONE" })
  hl(0, "NvimTreeCursorLine", { fg = "NONE", bg = colors.cursorD })
  hl(0, "NvimTreeGitStaged", { fg = colors.String, bg = "NONE" })
  hl(0, "NvimTreeGitMerge", { fg = colors.yellow, bg = "NONE" })
  hl(0, "NvimTreeGitRenamed", { fg = colors.aqua, bg = "NONE" })
  hl(0, "NvimTreeGitIgnored", { fg = colors.comment, bg = "NONE" })

  -- Completion (nvim-cmp)
  hl(0, "CmpItemAbbrDeprecated", { fg = colors.gris, bg = "NONE", strikethrough = true })
  hl(0, "CmpItemAbbrMatch", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "CmpItemAbbrMatchFuzzy", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "CmpItemKindVariable", { fg = colors.Variable, bg = "NONE" })
  hl(0, "CmpItemKindInterface", { fg = colors.Type, bg = "NONE" })
  hl(0, "CmpItemKindText", { fg = colors.fg, bg = "NONE" })
  hl(0, "CmpItemKindFunction", { fg = colors.FuncCall, bg = "NONE" })
  hl(0, "CmpItemKindMethod", { fg = colors.FuncCall, bg = "NONE" })
  hl(0, "CmpItemKindKeyword", { fg = colors.Keyword, bg = "NONE" })
  hl(0, "CmpItemKindProperty", { fg = colors.props, bg = "NONE" })
  hl(0, "CmpItemKindUnit", { fg = colors.Number, bg = "NONE" })
  hl(0, "CmpItemKindConstructor", { fg = colors.ClassCall, bg = "NONE" })
  hl(0, "CmpItemKindClass", { fg = colors.ClassName, bg = "NONE" })
  hl(0, "CmpItemKindModule", { fg = colors.aqua, bg = "NONE" })
  hl(0, "CmpItemKindOperator", { fg = colors.operator, bg = "NONE" })
  hl(0, "CmpItemKindField", { fg = colors.props, bg = "NONE" })
  hl(0, "CmpItemKindTypeParameter", { fg = colors.Type, bg = "NONE" })
  hl(0, "CmpItemKindEnum", { fg = colors.Type, bg = "NONE" })
  hl(0, "CmpItemKindStruct", { fg = colors.Type, bg = "NONE" })
  hl(0, "CmpItemKindConstant", { fg = colors.Constant, bg = "NONE" })
  hl(0, "CmpItemKindSnippet", { fg = colors.special, bg = "NONE" })
  hl(0, "CmpItemMenu", { fg = colors.comment, bg = "NONE" })

  -- GitSigns
  hl(0, "GitSignsAdd", { fg = colors.String, bg = "NONE" })
  hl(0, "GitSignsChange", { fg = colors.yellow, bg = "NONE" })
  hl(0, "GitSignsDelete", { fg = colors.red, bg = "NONE" })

  -- Dashboard
  hl(0, "DashboardHeader", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "DashboardCenter", { fg = colors.fg, bg = "NONE" })
  hl(0, "DashboardShortCut", { fg = colors.yellow, bg = "NONE" })
  hl(0, "DashboardFooter", { fg = colors.comment, bg = "NONE", italic = true })

  -- WhichKey
  hl(0, "WhichKey", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "WhichKeyGroup", { fg = colors.yellow, bg = "NONE" })
  hl(0, "WhichKeyDesc", { fg = colors.fg, bg = "NONE" })
  hl(0, "WhichKeySeparator", { fg = colors.gris, bg = "NONE" })
  hl(0, "WhichKeyFloat", { fg = colors.fg, bg = colors.gray })
  hl(0, "WhichKeyValue", { fg = colors.comment, bg = "NONE" })

  -- IndentBlankline
  hl(0, "IndentBlanklineChar", { fg = colors.gray, bg = "NONE" })
  hl(0, "IndentBlanklineContextChar", { fg = colors.gris, bg = "NONE" })

  -- Trouble
  hl(0, "TroubleText", { fg = colors.fg, bg = "NONE" })
  hl(0, "TroubleCount", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "TroubleNormal", { fg = colors.fg, bg = "NONE" })

  -- BufferLine
  hl(0, "BufferLineIndicatorSelected", { fg = colors.aqua, bg = "NONE" })
  hl(0, "BufferLineFill", { fg = "NONE", bg = colors.black })

  -- [[ Yazi.nvim ]] --
  hl(0, "YaziBorder", { fg = colors.gris, bg = "NONE" })
  hl(0, "YaziHeader", { fg = colors.aqua, bg = "NONE", bold = true })
  hl(0, "YaziFolder", { fg = colors.aqua, bg = "NONE" })
  hl(0, "YaziFile", { fg = colors.fg, bg = "NONE" })
  hl(0, "YaziSymlink", { fg = colors.aqua, bg = "NONE", italic = true })
  hl(0, "YaziSelection", { fg = "NONE", bg = colors.cursorD })
  hl(0, "YaziSelectionFolder", { fg = colors.aqua, bg = colors.cursorD, bold = true })
  hl(0, "YaziSelectionFile", { fg = colors.fg, bg = colors.cursorD })
end

return theme
